que1- Write a Python Program to Add Two Matrices?

ans1- 

In [2]:
import numpy as np
mat1 = np.array([[1,2,3],
        [4,5,6],
        [7,8,9]])
mat2 = np.array([[1,2,3],
        [4,5,6],
        [7,8,9]])
Matsum = np.add(mat1,mat2)
print("The Sum of two matrix \n\n{}  and \n\n{}  is \n\n{} ".format(mat1,mat2,Matsum))

The Sum of two matrix 

[[1 2 3]
 [4 5 6]
 [7 8 9]]  and 

[[1 2 3]
 [4 5 6]
 [7 8 9]]  is 

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]] 


que2- Write a Python Program to Multiply Two Matrices?

ans2- 

In [3]:
import numpy as np
mat1 = np.array([[1,2,3],
        [4,5,6],
        [7,8,9]])
mat2 = np.array([[1,2,3],
        [4,5,6],
        [7,8,9]])
mulMat = np.dot(mat1,mat2)
print("The product of two matrix \n\n{}  and \n\n{}  is \n\n{} ".format(mat1,mat2,mulMat))

The product of two matrix 

[[1 2 3]
 [4 5 6]
 [7 8 9]]  and 

[[1 2 3]
 [4 5 6]
 [7 8 9]]  is 

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]] 


que3- Write a Python Program to Transpose a Matrix?

ans3- 

In [5]:
import numpy 
mat1 = np.array([[1,2,3],
        [4,5,6],
        [7,8,9]])
print(mat1)
print("\n")
print("Tnasposed matrix",numpy.transpose(mat1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Tnasposed matrix [[1 4 7]
 [2 5 8]
 [3 6 9]]


que4- Write a Python Program to Sort Words in Alphabetic Order?

ans4- 

In [7]:
input_string = input("Enter string")
words = input_string.split()
words.sort()
for word in words:
    print(word)

Enter stringI love coading .
.
I
coading
love


que5- Write a Python Program to Remove Punctuation From a String?

ans5- 

In [10]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
input_string = input("Enter a string with punctuations:")
rem_punc = ""
for i in input_string:
    if i not in punctuations:
        rem_punc = rem_punc + i
print(rem_punc)

Enter a string with punctuations:Hurry!
Hurry
